# Hand recognition model
This code uses a random forest classifier

## Imports

In [15]:
!pip install --upgrade sklearn

import pandas as pd
import numpy as np
import sklearn.ensemble as ensemble

## Get preprocessed data

In [17]:
!wget https://raw.githubusercontent.com/SpacewaIker/AirDraw/main/train_x.csv
!wget https://raw.githubusercontent.com/SpacewaIker/AirDraw/main/test_x.csv

--2021-11-16 16:00:43--  https://raw.githubusercontent.com/SpacewaIker/AirDraw/main/train_x.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19531507 (19M) [text/plain]
Saving to: ‘train_x.csv’

train_x.csv         100%[===================>]  18.63M   123MB/s    in 0.2s    

2021-11-16 16:00:43 (123 MB/s) - ‘train_x.csv’ saved [19531507/19531507]

--2021-11-16 16:00:43--  https://raw.githubusercontent.com/SpacewaIker/AirDraw/main/test_x.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2164251 (2.1M) [text/plain]
Saving to: ‘

In [18]:
train_x = pd.read_csv('train_x.csv', index_col=0)
train_x.dropna(inplace=True)

print(train_x.info())
print(train_x)

<class 'pandas.core.frame.DataFrame'>
Index: 16200 entries, A/A1.jpg to V/V998.jpg
Data columns (total 64 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Command  16200 non-null  object 
 1   0        16200 non-null  float64
 2   1        16200 non-null  float64
 3   2        16200 non-null  float64
 4   3        16200 non-null  float64
 5   4        16200 non-null  float64
 6   5        16200 non-null  float64
 7   6        16200 non-null  float64
 8   7        16200 non-null  float64
 9   8        16200 non-null  float64
 10  9        16200 non-null  float64
 11  10       16200 non-null  float64
 12  11       16200 non-null  float64
 13  12       16200 non-null  float64
 14  13       16200 non-null  float64
 15  14       16200 non-null  float64
 16  15       16200 non-null  float64
 17  16       16200 non-null  float64
 18  17       16200 non-null  float64
 19  18       16200 non-null  float64
 20  19       16200 non-null  float64
 21  20   

In [19]:
# get array with labels only
y_train = train_x['Command']

# get array with features only and drop NaNs
x_train = train_x.iloc[:, 1:64]

print(y_train)
print(x_train)

File
A/A1.jpg        Ellipse
A/A10.jpg       Ellipse
A/A100.jpg      Ellipse
A/A1000.jpg     Ellipse
A/A1001.jpg     Ellipse
                 ...   
V/V989.jpg     Triangle
V/V99.jpg      Triangle
V/V990.jpg     Triangle
V/V996.jpg     Triangle
V/V998.jpg     Triangle
Name: Command, Length: 16200, dtype: object
                    0         1         2  ...        60        61        62
File                                       ...                              
A/A1.jpg    -0.003756  0.080883  0.032612  ... -0.012595  0.045449 -0.023966
A/A10.jpg   -0.005596  0.080807  0.045561  ... -0.010209  0.049343 -0.019856
A/A100.jpg   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
A/A1000.jpg -0.002892  0.081772  0.033408  ... -0.026531  0.037126 -0.027262
A/A1001.jpg  0.005875  0.083854  0.030589  ... -0.011564  0.046879 -0.030367
...               ...       ...       ...  ...       ...       ...       ...
V/V989.jpg   0.007171  0.090853  0.021682  ... -0.012653  0.039348 -0.0

## Random Forest Classifier

In [20]:
rfc = ensemble.RandomForestClassifier()
rfc.fit(x_train, y_train)

RandomForestClassifier()

## Preprocess testing images

In [21]:
test_x = pd.read_csv('test_x.csv', index_col=0)
test_x.dropna(inplace=True)

print(test_x.info())
print(test_x)

<class 'pandas.core.frame.DataFrame'>
Index: 1800 entries, A/A1004.jpg to V/V999.jpg
Data columns (total 64 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Command  1800 non-null   object 
 1   0        1800 non-null   float64
 2   1        1800 non-null   float64
 3   2        1800 non-null   float64
 4   3        1800 non-null   float64
 5   4        1800 non-null   float64
 6   5        1800 non-null   float64
 7   6        1800 non-null   float64
 8   7        1800 non-null   float64
 9   8        1800 non-null   float64
 10  9        1800 non-null   float64
 11  10       1800 non-null   float64
 12  11       1800 non-null   float64
 13  12       1800 non-null   float64
 14  13       1800 non-null   float64
 15  14       1800 non-null   float64
 16  15       1800 non-null   float64
 17  16       1800 non-null   float64
 18  17       1800 non-null   float64
 19  18       1800 non-null   float64
 20  19       1800 non-null   float64
 21  20 

In [22]:
# get array with labels only
y_test = test_x['Command']

# get array with features only and drop NaNs
x_test = test_x.iloc[:, 1:64]

print(y_test)
print(x_test)

File
A/A1004.jpg     Ellipse
A/A1014.jpg     Ellipse
A/A1072.jpg     Ellipse
A/A1078.jpg     Ellipse
A/A1085.jpg     Ellipse
                 ...   
V/V993.jpg     Triangle
V/V994.jpg     Triangle
V/V995.jpg     Triangle
V/V997.jpg     Triangle
V/V999.jpg     Triangle
Name: Command, Length: 1800, dtype: object
                    0         1         2  ...        60        61        62
File                                       ...                              
A/A1004.jpg  0.001602  0.085208  0.026555  ... -0.013341  0.045383 -0.031744
A/A1014.jpg -0.005892  0.079259  0.026053  ... -0.023837  0.040704 -0.029033
A/A1072.jpg -0.007961  0.076523  0.025876  ... -0.021562  0.037372 -0.028781
A/A1078.jpg -0.006064  0.079812  0.028786  ... -0.019958  0.039224 -0.030387
A/A1085.jpg -0.009182  0.083030  0.019311  ... -0.022091  0.036009 -0.032164
...               ...       ...       ...  ...       ...       ...       ...
V/V993.jpg   0.009097  0.091313  0.018784  ... -0.012648  0.037592 -0.01

## Predict test images

In [23]:
print('Training accuracy: ' + str(rfc.score(x_train, y_train)))
print('Testing accuracy: ' + str(rfc.score(x_test, y_test)))

y_pred = rfc.predict(x_test)

Training accuracy: 0.8991975308641975
Testing accuracy: 0.9016666666666666


## Confusion matrix

In [28]:
import sklearn.metrics as metrics
from matplotlib import pyplot as plt

labels = ['Line', 'Ellipse', 'Rectangle', 'Triangle', 'Move', 'Delete']

conf_matrix = metrics.confusion_matrix(y_test, y_pred, labels=labels)
print(conf_matrix)

[[263   1   0   0  32   0]
 [  0 286   0   0  35   0]
 [  0   0 243   0  50   0]
 [  0   0   0 273  25   0]
 [  0   0   1   0 302   0]
 [  0   0   0   0  33 256]]


## Save model to file

In [29]:
import pickle

with open('hand_recognition_model.pkl', 'wb') as file:
    pickle.dump(rfc, file)

In [30]:
!mv "hand_recognition_model.pkl" "drive/MyDrive/MAISFinalProject/hand_recognition_model.pkl"